site_name: "JavaScript DSA Notes"
site_url: https://yxshkm404.github.io/javascript-dsa-notes/
repo_url: https://github.com/yxshkm404/javascript-dsa-notes
repo_name: GitHub

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: deeporange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deeporange
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono


nav:
  - Home: index.md

  - Basics:
      - Asymptotic Notations: Basics/Asymptotic-Notations.md
      - Functions: Basics/functions.md
      - Loops: Basics/loops.md
      - Methods: Basics/methods.md
      - OOPs: Basics/oops.md
      - Variables: Basics/variables.md

  - Algorithms:
      - Dynamic Programming: Algorithms/dynamic-programming.md
      - Greedy: Algorithms/greedy.md
      - Misc: Algorithms/misc.md
      - Recursion: Algorithms/recursion.md
      - Searching: Algorithms/searching.md
      - Sorting: Algorithms/sorting.md

  - Data Structures:
      - Arrays: Data-Structures/arrays.md
      - Doubly Linked List: Data-Structures/Doubly-linked-list.md
      - Graph: Data-Structures/graph.md
      - Hash Map: Data-Structures/hash-map.md
      - Linked List: Data-Structures/linked-list.md
      - Map: Data-Structures/map.md
      - Object: Data-Structures/object.md
      - Queue: Data-Structures/queue.md
      - Sets: Data-Structures/sets.md
      - Stack: Data-Structures/stack.md
      - Strings: Data-Structures/strings.md
      - Tree: Data-Structures/tree.md

  - Practice Problems:
      - Easy: Practice/easy.md
      - Medium: Practice/medium.md
      - Hard: Practice/hard.md
